### PR TITLE
Removing user details like email/username in Json Response in local_signin

### PR DESCRIPTION
**Pull request by snehasischatterjee**
Before when user logins to Local_signin, it doesn't matter with what details user logins to the portal but the email of the logging user is visible in the json response in the console. Now, if user logins with username then the username will only be visible in the console and if user login with email then only email can be visible in the console as Json Response.

@MrJons @hannahlillis @udayavado @ajaySurti @vijay @celine
Screenshot from 2019-05-03 15-59-36

### CODE REVIEW

**Comment by tamasmagyarhunor88** [comment]
I've had a look on dotnative (it uses this plugin and allows e-mail login) and following errors happen when I try to log in with a valid e-mail address

http://null/local/signin/index.php?username=admin@user.com
This site can’t be reached null’s server IP address could not be found.
DNS_PROBE_FINISHED_NXDOMAIN

And altough Avado doesn't have e-mail login enabled, if I try to use my email there, the response for userdetails is just null:
"[{"error":false,"data":{"domain":null,"userdetail":null}}]"

I guess this is why on dotnative it is throwing errors.

**Comment by snehasischatterjee** [comment]
> I've had a look on dotnative (it uses this plugin and allows e-mail login) and following erros happen:
> 
> http://null/local/signin/index.php?username=admin@user.com
> This site can’t be reached null’s server IP address could not be found.
> DNS_PROBE_FINISHED_NXDOMAIN


Can you please share the screenshot and can you please try again by clearing the cache.

**Comment by tamasmagyarhunor88** [comment]
> > I've had a look on dotnative (it uses this plugin and allows e-mail login) and following erros happen:
> > http://null/local/signin/index.php?username=admin@user.com
> > This site can’t be reached null’s server IP address could not be found.
> > DNS_PROBE_FINISHED_NXDOMAIN
> 
> Can you please share the screenshot and can you please try again by clearing the cache.

Hey Snehasis,
good catch, I've cleared caches and it all works fine now.

**Review by MrJons — APPROVED** [review]
Looks good

**Review by ajayksurti — APPROVED** [review]

**Review by MrJons — APPROVED** [review]

**Pull request merged**
